create table cidade (id bigserial not null, nome varchar(255) not null, estado_id bigint not null, primary key (id));
create table cozinha (id bigserial not null, nome varchar(255) not null, primary key (id));
create table estado (id bigserial not null, nome varchar(255) not null, primary key (id));
create table forma_pagamento (id bigserial not null, descricao varchar(255) not null, primary key (id));
create table grupo (id bigserial not null, nome varchar(255) not null, primary key (id));
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null);
create table permissao (id bigserial not null, descricao varchar(255) not null, nome varchar(255) not null, primary key (id));
create table produto (id bigserial not null, ativo boolean not null, descricao varchar(255) not null, nome varchar(255) not null, preco numeric(38,2) not null, restaurante_id bigint not null, primary key (id));
create table restaurante (id bigserial not null, data_atualizacao timestamp(0) not null, data_cadastro timestamp(0) not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(38,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id));
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null);
create table usuario (id bigserial not null, data_cadastro timestamp(0) not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id));
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao;
alter table if exists grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
insert into cozinha (id, nome) values (100, 'Tailandesa');
insert into cozinha (id, nome) values (200, 'Indiana');
insert into estado (id, nome) values (100, 'Pará');
insert into estado (id, nome) values (200, 'Amapá');
insert into estado (id, nome) values (300, 'Ceará');
insert into cidade (id, nome, estado_id) values (100, 'Belém', 100);
insert into cidade (id, nome, estado_id) values (200, 'Ananindeua', 100);
insert into cidade (id, nome, estado_id) values (300, 'Macapá', 200);
insert into cidade (id, nome, estado_id) values (400, 'Santana', 200);
insert into cidade (id, nome, estado_id) values (500, 'Fortaleza', 300);
insert into restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_logradouro, endereco_numero, endereco_bairro, endereco_cep) values (100, 'Thai Gourmet', 10, 100, current_timestamp, current_timestamp, 100,'Rua Quatorze A', 41, 'Maracangalha', '66110-058');
insert into restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_logradouro, endereco_numero, endereco_bairro, endereco_cep) values (200, 'Thai Delivery', 9.50, 100, current_timestamp, current_timestamp, 200,'Av. Poeta Castro Alves', 1451,'Central', '66009-123');
insert into restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_logradouro, endereco_numero, endereco_bairro, endereco_cep) values (300, 'Tuk Tuk Comida Indiana', 15, 200, current_timestamp, current_timestamp, 300,'Rua Cearense',229,'Bom Passos','54231-548');
insert into forma_pagamento (id, descricao) values (100, 'Cartão de crédito');
insert into forma_pagamento (id, descricao) values (200, 'Cartão de débito');
insert into forma_pagamento (id, descricao) values (300, 'Dinheiro');
insert into permissao (id, nome, descricao) values (100, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into permissao (id, nome, descricao) values (200, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (100, 100),(100,200),(100,300),(200,300),(300,200),(300,300);
create table cidade (id bigserial not null, nome varchar(255) not null, estado_id bigint not null, primary key (id));
create table cozinha (id bigserial not null, nome varchar(255) not null, primary key (id));
create table estado (id bigserial not null, nome varchar(255) not null, primary key (id));
create table forma_pagamento (id bigserial not null, descricao varchar(255) not null, primary key (id));
create table grupo (id bigserial not null, nome varchar(255) not null, primary key (id));
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null);
create table permissao (id bigserial not null, descricao varchar(255) not null, nome varchar(255) not null, primary key (id));
create table produto (id bigserial not null, ativo boolean not null, descricao varchar(255) not null, nome varchar(255) not null, preco numeric(38,2) not null, restaurante_id bigint not null, primary key (id));
create table restaurante (id bigserial not null, data_atualizacao timestamp(0) not null, data_cadastro timestamp(0) not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(38,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id));
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null);
create table usuario (id bigserial not null, data_cadastro timestamp(0) not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id));
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao;
alter table if exists grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
insert into cozinha (id, nome) values (100, 'Tailandesa');
insert into cozinha (id, nome) values (200, 'Indiana');
insert into estado (id, nome) values (100, 'Pará');
insert into estado (id, nome) values (200, 'Amapá');
insert into estado (id, nome) values (300, 'Ceará');
insert into cidade (id, nome, estado_id) values (100, 'Belém', 100);
insert into cidade (id, nome, estado_id) values (200, 'Ananindeua', 100);
insert into cidade (id, nome, estado_id) values (300, 'Macapá', 200);
insert into cidade (id, nome, estado_id) values (400, 'Santana', 200);
insert into cidade (id, nome, estado_id) values (500, 'Fortaleza', 300);
insert into restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_logradouro, endereco_numero, endereco_bairro, endereco_cep) values (100, 'Thai Gourmet', 10, 100, current_timestamp, current_timestamp, 100,'Rua Quatorze A', 41, 'Maracangalha', '66110-058');
insert into restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_logradouro, endereco_numero, endereco_bairro, endereco_cep) values (200, 'Thai Delivery', 9.50, 100, current_timestamp, current_timestamp, 200,'Av. Poeta Castro Alves', 1451,'Central', '66009-123');
insert into restaurante (id, nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao, endereco_cidade_id, endereco_logradouro, endereco_numero, endereco_bairro, endereco_cep) values (300, 'Tuk Tuk Comida Indiana', 15, 200, current_timestamp, current_timestamp, 300,'Rua Cearense',229,'Bom Passos','54231-548');
insert into forma_pagamento (id, descricao) values (100, 'Cartão de crédito');
insert into forma_pagamento (id, descricao) values (200, 'Cartão de débito');
insert into forma_pagamento (id, descricao) values (300, 'Dinheiro');
insert into permissao (id, nome, descricao) values (100, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into permissao (id, nome, descricao) values (200, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into restaurante_forma_pagamento(restaurante_id, forma_pagamento_id) values (100, 100),(100,200),(100,300),(200,300),(300,200),(300,300);
